version: '2'
services:
  mongo:
    image: mongo:3.0.11
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
        - .:/data
  redis:
    image: redis:2.8.21
    ports:
      - "6379:6379"
    volumes:
        - .:/data